### PR TITLE
Implemented page designs and Checkout

### PR DESCRIPTION
**Pull request by JaxChua**
Feel free to change the page design.

### CODE REVIEW

**Comment by JaxChua** [comment]
Undefined variable $disc in shoppingCart.php on line 261.  Error from merging and accepting incoming changes.

**Comment by CaeNGnp** [comment]
lookie good, will work from this

**Comment by Kwongmingwei** [comment]
Fixed "undefined variable $disc in shoppingcart"

**Comment by CaeNGnp** [comment]
will merge this in first to save time ^^

tq for setting up most of the pages already

**Pull request merged**
